///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SCO_Test.Recording_Modules.PickListRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The test_pickBuy3GetOneFree recording.
    /// </summary>
    [TestModule("f0bf1039-0dfd-4cec-9d5a-e7e96ee75545", ModuleType.Recording, 1)]
    public partial class test_pickBuy3GetOneFree : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SCO_Test.SCO_TestRepository repository.
        /// </summary>
        public static global::SCO_Test.SCO_TestRepository repo = global::SCO_Test.SCO_TestRepository.Instance;

        static test_pickBuy3GetOneFree instance = new test_pickBuy3GetOneFree();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public test_pickBuy3GetOneFree()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static test_pickBuy3GetOneFree Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SearchOrKeyInItem1' at Center.", repo.NCRNEXTGENUI2.SearchOrKeyInItem1Info, new RecordItemIndex(0));
            repo.NCRNEXTGENUI2.SearchOrKeyInItem1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeListItem11' at Center.", repo.NCRNEXTGENUI2.SomeListItem11Info, new RecordItemIndex(2));
            repo.NCRNEXTGENUI2.SomeListItem11.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeListItem1' at Center.", repo.NCRNEXTGENUI2.SomeListItem1Info, new RecordItemIndex(4));
            repo.NCRNEXTGENUI2.SomeListItem1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SearchOrKeyInItem' at Center.", repo.NCRNEXTGENUI2.SearchOrKeyInItemInfo, new RecordItemIndex(6));
            repo.NCRNEXTGENUI2.SearchOrKeyInItem.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeListItem11' at Center.", repo.NCRNEXTGENUI2.SomeListItem11Info, new RecordItemIndex(8));
            repo.NCRNEXTGENUI2.SomeListItem11.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeListItem1' at Center.", repo.NCRNEXTGENUI2.SomeListItem1Info, new RecordItemIndex(10));
            repo.NCRNEXTGENUI2.SomeListItem1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(11));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SearchOrKeyInItem' at Center.", repo.NCRNEXTGENUI2.SearchOrKeyInItemInfo, new RecordItemIndex(12));
            repo.NCRNEXTGENUI2.SearchOrKeyInItem.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(13));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeListItem11' at Center.", repo.NCRNEXTGENUI2.SomeListItem11Info, new RecordItemIndex(14));
            repo.NCRNEXTGENUI2.SomeListItem11.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(15));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeListItem1' at Center.", repo.NCRNEXTGENUI2.SomeListItem1Info, new RecordItemIndex(16));
            repo.NCRNEXTGENUI2.SomeListItem1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(17));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cadbury Bitsa Wispa 95g') on item 'NCRNEXTGENUI2.CartControl.ItemDescription3'.", repo.NCRNEXTGENUI2.CartControl.ItemDescription3Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.CartControl.ItemDescription3Info, "Text", "Cadbury Bitsa Wispa 95g");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='    DISCOUNT') on item 'NCRNEXTGENUI2.CartControl.ItemDescription'.", repo.NCRNEXTGENUI2.CartControl.ItemDescriptionInfo, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.CartControl.ItemDescriptionInfo, "Text", "    DISCOUNT");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cadbury Bitsa Wispa 95g') on item 'NCRNEXTGENUI2.CartControl.ItemDescription2'.", repo.NCRNEXTGENUI2.CartControl.ItemDescription2Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.CartControl.ItemDescription2Info, "Text", "Cadbury Bitsa Wispa 95g");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Cadbury Bitsa Wispa 95g') on item 'NCRNEXTGENUI2.CartControl.ItemDescription1'.", repo.NCRNEXTGENUI2.CartControl.ItemDescription1Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.CartControl.ItemDescription1Info, "Text", "Cadbury Bitsa Wispa 95g");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='€3.00') on item 'NCRNEXTGENUI2.CartControl.TotalAmountValue'.", repo.NCRNEXTGENUI2.CartControl.TotalAmountValueInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.CartControl.TotalAmountValueInfo, "Text", "€3.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(23));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.PayButton' at Center.", repo.NCRNEXTGENUI2.PayButtonInfo, new RecordItemIndex(24));
            repo.NCRNEXTGENUI2.PayButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(25));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.Tender4' at Center.", repo.NCRNEXTGENUI2.Tender4Info, new RecordItemIndex(26));
            repo.NCRNEXTGENUI2.Tender4.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(27));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Thanks for shopping with us.') on item 'NCRNEXTGENUI2.HeaderText'.", repo.NCRNEXTGENUI2.HeaderTextInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.HeaderTextInfo, "Text", "Thanks for shopping with us.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(29));
            Delay.Duration(300, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
