///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SCO_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SCO_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fc1d2383-1ec3-4156-b397-7cdcc4b2ac47")]
    public partial class SCO_TestRepository : RepoGenBaseFolder
    {
        static SCO_TestRepository instance = new SCO_TestRepository();
        SCO_TestRepositoryFolders.LaunchPadNetAppFolder _launchpadnet;
        SCO_TestRepositoryFolders.NCRNEXTGENUIAppFolder _ncrnextgenui;

        /// <summary>
        /// Gets the singleton class instance representing the SCO_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("fc1d2383-1ec3-4156-b397-7cdcc4b2ac47")]
        public static SCO_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SCO_TestRepository() 
            : base("SCO_TestRepository", "/", null, 0, false, "fc1d2383-1ec3-4156-b397-7cdcc4b2ac47", ".\\RepositoryImages\\SCO_TestRepositoryfc1d2383.rximgres")
        {
            _launchpadnet = new SCO_TestRepositoryFolders.LaunchPadNetAppFolder(this);
            _ncrnextgenui = new SCO_TestRepositoryFolders.NCRNEXTGENUIAppFolder(this);
        }

#region Variables

        string _KeypadList = "";

        /// <summary>
        /// Gets or sets the value of variable KeypadList.
        /// </summary>
        [TestVariable("0e5672c7-c258-49a0-a917-13cbdcf9e69c")]
        public string KeypadList
        {
            get { return _KeypadList; }
            set { _KeypadList = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fc1d2383-1ec3-4156-b397-7cdcc4b2ac47")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LaunchPadNet folder.
        /// </summary>
        [RepositoryFolder("2cae00d9-d291-4a14-ae96-fbce08b08210")]
        public virtual SCO_TestRepositoryFolders.LaunchPadNetAppFolder LaunchPadNet
        {
            get { return _launchpadnet; }
        }

        /// <summary>
        /// The NCRNEXTGENUI folder.
        /// </summary>
        [RepositoryFolder("800862a7-99c5-4a63-843a-9dcbb720f387")]
        public virtual SCO_TestRepositoryFolders.NCRNEXTGENUIAppFolder NCRNEXTGENUI
        {
            get { return _ncrnextgenui; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SCO_TestRepositoryFolders
    {
        /// <summary>
        /// The LaunchPadNetAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cae00d9-d291-4a14-ae96-fbce08b08210")]
        public partial class LaunchPadNetAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new LaunchPadNet  folder.
            /// </summary>
            public LaunchPadNetAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LaunchPadNet", "/form[@title='LaunchPadNet']", parentFolder, 30000, null, false, "2cae00d9-d291-4a14-ae96-fbce08b08210", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cae00d9-d291-4a14-ae96-fbce08b08210")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cae00d9-d291-4a14-ae96-fbce08b08210")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The NCRNEXTGENUIAppFolder folder.
        /// </summary>
        [RepositoryFolder("800862a7-99c5-4a63-843a-9dcbb720f387")]
        public partial class NCRNEXTGENUIAppFolder : RepoGenBaseFolder
        {
            SCO_TestRepositoryFolders.SomeContainerFolder _somecontainer;
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _searchkeyinitembuttonInfo;
            RepoItemInfo _pluitembtn1Info;
            RepoItemInfo _paybuttonInfo;
            RepoItemInfo _clubcardnobtnInfo;
            RepoItemInfo _fakecashbtnInfo;
            RepoItemInfo _receiptimgInfo;
            RepoItemInfo _totalamountvalueInfo;
            RepoItemInfo _payamountvalueInfo;
            RepoItemInfo _amountpaidInfo;
            RepoItemInfo _keypad1Info;
            RepoItemInfo _editcartbtnInfo;
            RepoItemInfo _cancelallbtnInfo;
            RepoItemInfo _yesemptycartbtnInfo;
            RepoItemInfo _yescancelallitemsbtnInfo;
            RepoItemInfo _scanitemsearchkeyinitemInfo;
            RepoItemInfo _cartreceiptInfo;

            /// <summary>
            /// Creates a new NCRNEXTGENUI  folder.
            /// </summary>
            public NCRNEXTGENUIAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NCRNEXTGENUI", "/form[@title='NCR NEXTGENUI']", parentFolder, 30000, null, false, "800862a7-99c5-4a63-843a-9dcbb720f387", "")
            {
                _somecontainer = new SCO_TestRepositoryFolders.SomeContainerFolder(this);
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "container[@caption='']/container[@caption='']/container[5]/button[@automationid='OK_Button']", ".//button[@automationid='OK_Button']", 30000, null, "88055d48-5532-449f-94b1-aa162538b526");
                _searchkeyinitembuttonInfo = new RepoItemInfo(this, "SearchKeyInItemButton", "button[@automationid='InstructionBox']/container[@automationid='ScanItemStatus']/button[@automationid='SearchKeyInItemButton']", ".//button[@automationid='SearchKeyInItemButton']", 30000, null, "19dc16a4-3c39-4b1a-8f00-279461e095cc");
                _pluitembtn1Info = new RepoItemInfo(this, "pluItemBTN1", "container[@automationid='SearchListGrid']/list[@automationid='SearchList']/container[2]/listitem[@index='0']", "?/?/list[@automationid='SearchList']/container[2]/listitem[@index='0']", 30000, null, "99524969-b4dd-4e14-a288-a3d00feb32f8");
                _paybuttonInfo = new RepoItemInfo(this, "PayButton", "container[@automationid='CartControl']/button[@automationid='PayButton']", "?/?/button[@automationid='PayButton']", 30000, null, "613a690f-6d20-4efe-97d5-1849e0b02378");
                _clubcardnobtnInfo = new RepoItemInfo(this, "clubcardNoBtn", "container[@caption='']/container[2]/button[@automationid='List2Button']", ".//button[@automationid='List2Button']", 30000, null, "404c4172-cd81-4814-8250-dca59f8a1fac");
                _fakecashbtnInfo = new RepoItemInfo(this, "fakeCashBtn", "container[@automationid='MainPayment']/container[2]/button[@automationid='Tender4']", ".//button[@automationid='Tender4']", 30000, null, "b196f19d-7590-485f-b3d9-d55c00c2b3ab");
                _receiptimgInfo = new RepoItemInfo(this, "receiptImg", "container[@caption='']/picture", "container[@caption='']/picture", 30000, null, "16029742-84cf-460e-ab01-b0eeb7a982ba");
                _totalamountvalueInfo = new RepoItemInfo(this, "TotalAmountValue", "container[@automationid='CartControl']/container[2]/text[@automationid='TotalAmountValue']", ".//text[@automationid='TotalAmountValue']", 30000, null, "4f0a5bad-ed5e-4875-9072-7747a874bd9f");
                _payamountvalueInfo = new RepoItemInfo(this, "PayAmountValue", "container[@automationid='CartControl']/button[@automationid='PayButton']/text[@automationid='PayTitleText']/text[@automationid='PayAmountValue']", ".//text[@automationid='PayAmountValue']", 30000, null, "5d108e9d-9110-4b75-b4d4-7ad2beb34f74");
                _amountpaidInfo = new RepoItemInfo(this, "AmountPaid", "container[@caption='']/container[@caption='']/container[2]/text[@automationid='AmountPaid']", ".//text[@automationid='AmountPaid']", 30000, null, "acc665b4-3c02-46e7-b021-4553ad6e0bb9");
                _keypad1Info = new RepoItemInfo(this, "keypad1", "container[@caption='']/button[@automationid='EnterButton']/list[@automationid='NumericLine1Keys']/button[@name='LineKeys' and @text='1']", ".//button[@name='LineKeys' and @text='1']", 30000, null, "30a4c094-f538-43c1-bf76-8bd96e86cc40");
                _editcartbtnInfo = new RepoItemInfo(this, "EditCartBtn", "container[@automationid='CartControl']/container[1]/button[@automationid='EditCartBtn']", ".//button[@automationid='EditCartBtn']", 30000, null, "3a88c3c7-8168-49b0-adba-eae6794ec041");
                _cancelallbtnInfo = new RepoItemInfo(this, "CancelAllBtn", "container[@automationid='CartControl']/container[1]/button[@automationid='CancelAllBtn']", ".//button[@automationid='CancelAllBtn']", 30000, null, "8b684d39-a138-46aa-b9d5-18b92ebfeba1");
                _yesemptycartbtnInfo = new RepoItemInfo(this, "yesEmptyCartBtn", "container[@automationid='ConfirmAbortPanel']/container[2]/button[@automationid='YesButton']", ".//button[@automationid='YesButton']", 30000, null, "5fe00bb6-1881-4a42-a16e-5bf8c529b824");
                _yescancelallitemsbtnInfo = new RepoItemInfo(this, "yesCancelAllItemsBtn", "list[@automationid='ContainerStoreModeButtonsItemsControl']/button[@automationid='StoreButton1']", "?/?/button[@automationid='StoreButton1']", 30000, null, "9b862be0-faf8-416c-ae0e-b9da3d0ac545");
                _scanitemsearchkeyinitemInfo = new RepoItemInfo(this, "ScanItemSearchKeyInItem", "container[@automationid='ScanItemStatus']/button[@automationid='ScanItemSearchKeyInItem']", "?/?/button[@automationid='ScanItemSearchKeyInItem']", 30000, null, "b3d74d39-3281-41e7-be2d-53a1256bf535");
                _cartreceiptInfo = new RepoItemInfo(this, "CartReceipt", "container[@automationid='CartControl']/list[@automationid='CartReceipt']", "?/?/list[@automationid='CartReceipt']", 30000, null, "de5aaa04-99f8-4f5e-ba77-61a0de9640b4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("800862a7-99c5-4a63-843a-9dcbb720f387")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("800862a7-99c5-4a63-843a-9dcbb720f387")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("88055d48-5532-449f-94b1-aa162538b526")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("88055d48-5532-449f-94b1-aa162538b526")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The SearchKeyInItemButton item.
            /// </summary>
            [RepositoryItem("19dc16a4-3c39-4b1a-8f00-279461e095cc")]
            public virtual Ranorex.Button SearchKeyInItemButton
            {
                get
                {
                    return _searchkeyinitembuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SearchKeyInItemButton item info.
            /// </summary>
            [RepositoryItemInfo("19dc16a4-3c39-4b1a-8f00-279461e095cc")]
            public virtual RepoItemInfo SearchKeyInItemButtonInfo
            {
                get
                {
                    return _searchkeyinitembuttonInfo;
                }
            }

            /// <summary>
            /// The pluItemBTN1 item.
            /// </summary>
            [RepositoryItem("99524969-b4dd-4e14-a288-a3d00feb32f8")]
            public virtual Ranorex.ListItem pluItemBTN1
            {
                get
                {
                    return _pluitembtn1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The pluItemBTN1 item info.
            /// </summary>
            [RepositoryItemInfo("99524969-b4dd-4e14-a288-a3d00feb32f8")]
            public virtual RepoItemInfo pluItemBTN1Info
            {
                get
                {
                    return _pluitembtn1Info;
                }
            }

            /// <summary>
            /// The PayButton item.
            /// </summary>
            [RepositoryItem("613a690f-6d20-4efe-97d5-1849e0b02378")]
            public virtual Ranorex.Button PayButton
            {
                get
                {
                    return _paybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PayButton item info.
            /// </summary>
            [RepositoryItemInfo("613a690f-6d20-4efe-97d5-1849e0b02378")]
            public virtual RepoItemInfo PayButtonInfo
            {
                get
                {
                    return _paybuttonInfo;
                }
            }

            /// <summary>
            /// The clubcardNoBtn item.
            /// </summary>
            [RepositoryItem("404c4172-cd81-4814-8250-dca59f8a1fac")]
            public virtual Ranorex.Button clubcardNoBtn
            {
                get
                {
                    return _clubcardnobtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The clubcardNoBtn item info.
            /// </summary>
            [RepositoryItemInfo("404c4172-cd81-4814-8250-dca59f8a1fac")]
            public virtual RepoItemInfo clubcardNoBtnInfo
            {
                get
                {
                    return _clubcardnobtnInfo;
                }
            }

            /// <summary>
            /// The fakeCashBtn item.
            /// </summary>
            [RepositoryItem("b196f19d-7590-485f-b3d9-d55c00c2b3ab")]
            public virtual Ranorex.Button fakeCashBtn
            {
                get
                {
                    return _fakecashbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The fakeCashBtn item info.
            /// </summary>
            [RepositoryItemInfo("b196f19d-7590-485f-b3d9-d55c00c2b3ab")]
            public virtual RepoItemInfo fakeCashBtnInfo
            {
                get
                {
                    return _fakecashbtnInfo;
                }
            }

            /// <summary>
            /// The receiptImg item.
            /// </summary>
            [RepositoryItem("16029742-84cf-460e-ab01-b0eeb7a982ba")]
            public virtual Ranorex.Picture receiptImg
            {
                get
                {
                    return _receiptimgInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The receiptImg item info.
            /// </summary>
            [RepositoryItemInfo("16029742-84cf-460e-ab01-b0eeb7a982ba")]
            public virtual RepoItemInfo receiptImgInfo
            {
                get
                {
                    return _receiptimgInfo;
                }
            }

            /// <summary>
            /// The TotalAmountValue item.
            /// </summary>
            [RepositoryItem("4f0a5bad-ed5e-4875-9072-7747a874bd9f")]
            public virtual Ranorex.Text TotalAmountValue
            {
                get
                {
                    return _totalamountvalueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TotalAmountValue item info.
            /// </summary>
            [RepositoryItemInfo("4f0a5bad-ed5e-4875-9072-7747a874bd9f")]
            public virtual RepoItemInfo TotalAmountValueInfo
            {
                get
                {
                    return _totalamountvalueInfo;
                }
            }

            /// <summary>
            /// The PayAmountValue item.
            /// </summary>
            [RepositoryItem("5d108e9d-9110-4b75-b4d4-7ad2beb34f74")]
            public virtual Ranorex.Text PayAmountValue
            {
                get
                {
                    return _payamountvalueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PayAmountValue item info.
            /// </summary>
            [RepositoryItemInfo("5d108e9d-9110-4b75-b4d4-7ad2beb34f74")]
            public virtual RepoItemInfo PayAmountValueInfo
            {
                get
                {
                    return _payamountvalueInfo;
                }
            }

            /// <summary>
            /// The AmountPaid item.
            /// </summary>
            [RepositoryItem("acc665b4-3c02-46e7-b021-4553ad6e0bb9")]
            public virtual Ranorex.Text AmountPaid
            {
                get
                {
                    return _amountpaidInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AmountPaid item info.
            /// </summary>
            [RepositoryItemInfo("acc665b4-3c02-46e7-b021-4553ad6e0bb9")]
            public virtual RepoItemInfo AmountPaidInfo
            {
                get
                {
                    return _amountpaidInfo;
                }
            }

            /// <summary>
            /// The keypad1 item.
            /// </summary>
            [RepositoryItem("30a4c094-f538-43c1-bf76-8bd96e86cc40")]
            public virtual Ranorex.Button keypad1
            {
                get
                {
                    return _keypad1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad1 item info.
            /// </summary>
            [RepositoryItemInfo("30a4c094-f538-43c1-bf76-8bd96e86cc40")]
            public virtual RepoItemInfo keypad1Info
            {
                get
                {
                    return _keypad1Info;
                }
            }

            /// <summary>
            /// The EditCartBtn item.
            /// </summary>
            [RepositoryItem("3a88c3c7-8168-49b0-adba-eae6794ec041")]
            public virtual Ranorex.Button EditCartBtn
            {
                get
                {
                    return _editcartbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EditCartBtn item info.
            /// </summary>
            [RepositoryItemInfo("3a88c3c7-8168-49b0-adba-eae6794ec041")]
            public virtual RepoItemInfo EditCartBtnInfo
            {
                get
                {
                    return _editcartbtnInfo;
                }
            }

            /// <summary>
            /// The CancelAllBtn item.
            /// </summary>
            [RepositoryItem("8b684d39-a138-46aa-b9d5-18b92ebfeba1")]
            public virtual Ranorex.Button CancelAllBtn
            {
                get
                {
                    return _cancelallbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelAllBtn item info.
            /// </summary>
            [RepositoryItemInfo("8b684d39-a138-46aa-b9d5-18b92ebfeba1")]
            public virtual RepoItemInfo CancelAllBtnInfo
            {
                get
                {
                    return _cancelallbtnInfo;
                }
            }

            /// <summary>
            /// The yesEmptyCartBtn item.
            /// </summary>
            [RepositoryItem("5fe00bb6-1881-4a42-a16e-5bf8c529b824")]
            public virtual Ranorex.Button yesEmptyCartBtn
            {
                get
                {
                    return _yesemptycartbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The yesEmptyCartBtn item info.
            /// </summary>
            [RepositoryItemInfo("5fe00bb6-1881-4a42-a16e-5bf8c529b824")]
            public virtual RepoItemInfo yesEmptyCartBtnInfo
            {
                get
                {
                    return _yesemptycartbtnInfo;
                }
            }

            /// <summary>
            /// The yesCancelAllItemsBtn item.
            /// </summary>
            [RepositoryItem("9b862be0-faf8-416c-ae0e-b9da3d0ac545")]
            public virtual Ranorex.Button yesCancelAllItemsBtn
            {
                get
                {
                    return _yescancelallitemsbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The yesCancelAllItemsBtn item info.
            /// </summary>
            [RepositoryItemInfo("9b862be0-faf8-416c-ae0e-b9da3d0ac545")]
            public virtual RepoItemInfo yesCancelAllItemsBtnInfo
            {
                get
                {
                    return _yescancelallitemsbtnInfo;
                }
            }

            /// <summary>
            /// The ScanItemSearchKeyInItem item.
            /// </summary>
            [RepositoryItem("b3d74d39-3281-41e7-be2d-53a1256bf535")]
            public virtual Ranorex.Button ScanItemSearchKeyInItem
            {
                get
                {
                    return _scanitemsearchkeyinitemInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ScanItemSearchKeyInItem item info.
            /// </summary>
            [RepositoryItemInfo("b3d74d39-3281-41e7-be2d-53a1256bf535")]
            public virtual RepoItemInfo ScanItemSearchKeyInItemInfo
            {
                get
                {
                    return _scanitemsearchkeyinitemInfo;
                }
            }

            /// <summary>
            /// The CartReceipt item.
            /// </summary>
            [RepositoryItem("de5aaa04-99f8-4f5e-ba77-61a0de9640b4")]
            public virtual Ranorex.List CartReceipt
            {
                get
                {
                    return _cartreceiptInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The CartReceipt item info.
            /// </summary>
            [RepositoryItemInfo("de5aaa04-99f8-4f5e-ba77-61a0de9640b4")]
            public virtual RepoItemInfo CartReceiptInfo
            {
                get
                {
                    return _cartreceiptInfo;
                }
            }

            /// <summary>
            /// The SomeContainer folder.
            /// </summary>
            [RepositoryFolder("649a6613-214f-44cd-a0b1-aef1d9fbffcc")]
            public virtual SCO_TestRepositoryFolders.SomeContainerFolder SomeContainer
            {
                get { return _somecontainer; }
            }
        }

        /// <summary>
        /// The SomeContainerFolder folder.
        /// </summary>
        [RepositoryFolder("649a6613-214f-44cd-a0b1-aef1d9fbffcc")]
        public partial class SomeContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _keypad2Info;
            RepoItemInfo _keypad3Info;
            RepoItemInfo _keypad4Info;
            RepoItemInfo _keypad5Info;
            RepoItemInfo _keypad6Info;
            RepoItemInfo _keypad7Info;
            RepoItemInfo _keypad8Info;
            RepoItemInfo _keypad9Info;
            RepoItemInfo _keypad0Info;
            RepoItemInfo _enterbuttonInfo;
            RepoItemInfo _storeloginInfo;
            RepoItemInfo _storeloginkeypad9Info;
            RepoItemInfo _storeloginokbtnInfo;

            /// <summary>
            /// Creates a new SomeContainer  folder.
            /// </summary>
            public SomeContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer", "container[@caption='']", parentFolder, 30000, null, false, "649a6613-214f-44cd-a0b1-aef1d9fbffcc", "")
            {
                _keypad2Info = new RepoItemInfo(this, "keypad2", "button[@automationid='EnterButton']/list[@automationid='NumericLine1Keys']/button[@name='LineKeys' and @text='2']", "button[@name='LineKeys' and @text='2']", 30000, null, "714d8fe9-97f4-4ba0-96cb-0734d37394bc");
                _keypad3Info = new RepoItemInfo(this, "keypad3", "button[@automationid='EnterButton']/list[@automationid='NumericLine1Keys']/button[@name='LineKeys' and @text='3']", "button[@name='LineKeys' and @text='3']", 30000, null, "a4cf8823-8454-4f2e-a39d-621894350989");
                _keypad4Info = new RepoItemInfo(this, "keypad4", "button[@automationid='EnterButton']/list[@automationid='NumericLine2Keys']/button[@name='LineKeys' and @text='4']", "button[@name='LineKeys' and @text='4']", 30000, null, "8563c268-2991-4464-8af1-d8c7206e6d6f");
                _keypad5Info = new RepoItemInfo(this, "keypad5", "button[@automationid='EnterButton']/list[@automationid='NumericLine2Keys']/button[@name='LineKeys' and @text='5']", "button[@name='LineKeys' and @text='5']", 30000, null, "1ec46429-65e9-46a3-91f4-96b58db4a37d");
                _keypad6Info = new RepoItemInfo(this, "keypad6", "button[@automationid='EnterButton']/list[@automationid='NumericLine2Keys']/button[@name='LineKeys' and @text='6']", "button[@name='LineKeys' and @text='6']", 30000, null, "f654682e-3c9c-4a5b-b6fa-7a2ccbb6f2e1");
                _keypad7Info = new RepoItemInfo(this, "keypad7", "button[@automationid='EnterButton']/list[@automationid='NumericLine3Keys']/button[@name='LineKeys' and @text='7']", "button[@name='LineKeys' and @text='7']", 30000, null, "1bac706b-38f2-418e-bbcb-5647fb7941d2");
                _keypad8Info = new RepoItemInfo(this, "keypad8", "button[@automationid='EnterButton']/list[@automationid='NumericLine3Keys']/button[@name='LineKeys' and @text='8']", "button[@name='LineKeys' and @text='8']", 30000, null, "4a1c3710-9089-4b9d-bf88-65aae847d1bb");
                _keypad9Info = new RepoItemInfo(this, "keypad9", "button[@automationid='EnterButton']/list[@automationid='NumericLine3Keys']/button[@name='LineKeys' and @text='9']", "button[@name='LineKeys' and @text='9']", 30000, null, "43db0f4b-1895-47c1-98ef-14a9fda4a0f1");
                _keypad0Info = new RepoItemInfo(this, "keypad0", "button[@automationid='EnterButton']/list[@automationid='NumericLine4Keys']/button[@automationid='LineKeys']", "button[@name='LineKeys' and @text='0']", 30000, null, "a5d7d031-563e-46b9-8b9a-7f3754be86d4");
                _enterbuttonInfo = new RepoItemInfo(this, "EnterButton", "button[@automationid='EnterButton']", "?/button[@automationid='EnterButton']", 30000, null, "2ce707c9-ad62-45f6-bc94-ebad5981a8b2");
                _storeloginInfo = new RepoItemInfo(this, "StoreLogIn", "container[@caption='']/container[6]/button[@automationid='StoreLogin']/text[@caption='Store Log In']", "button[@automationid='StoreLogin']/text[@caption='Store Log In']", 30000, null, "8ff6dc1d-3ab5-4b26-9826-dc47dd9facab");
                _storeloginkeypad9Info = new RepoItemInfo(this, "storeLoginKeypad9", "text[@automationid='InputTextBox']/container[@automationid='KeypadGrid']/container[@automationid='thirdRow']/button[@automationid='Keypad9']", "button[@automationid='Keypad9']", 30000, null, "c10db81a-bf65-47d5-8dd0-c745900ef3d1");
                _storeloginokbtnInfo = new RepoItemInfo(this, "storeLoginOkBtn", "text[@automationid='InputTextBox']/container[@automationid='KeypadGrid']/container[@automationid='lastRow']/button[@automationid='OKButton']", "button[@automationid='OKButton']", 30000, null, "e3335353-da32-4362-b552-d4f1c61ebcb1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("649a6613-214f-44cd-a0b1-aef1d9fbffcc")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("649a6613-214f-44cd-a0b1-aef1d9fbffcc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The keypad2 item.
            /// </summary>
            [RepositoryItem("714d8fe9-97f4-4ba0-96cb-0734d37394bc")]
            public virtual Ranorex.Button keypad2
            {
                get
                {
                    return _keypad2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad2 item info.
            /// </summary>
            [RepositoryItemInfo("714d8fe9-97f4-4ba0-96cb-0734d37394bc")]
            public virtual RepoItemInfo keypad2Info
            {
                get
                {
                    return _keypad2Info;
                }
            }

            /// <summary>
            /// The keypad3 item.
            /// </summary>
            [RepositoryItem("a4cf8823-8454-4f2e-a39d-621894350989")]
            public virtual Ranorex.Button keypad3
            {
                get
                {
                    return _keypad3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad3 item info.
            /// </summary>
            [RepositoryItemInfo("a4cf8823-8454-4f2e-a39d-621894350989")]
            public virtual RepoItemInfo keypad3Info
            {
                get
                {
                    return _keypad3Info;
                }
            }

            /// <summary>
            /// The keypad4 item.
            /// </summary>
            [RepositoryItem("8563c268-2991-4464-8af1-d8c7206e6d6f")]
            public virtual Ranorex.Button keypad4
            {
                get
                {
                    return _keypad4Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad4 item info.
            /// </summary>
            [RepositoryItemInfo("8563c268-2991-4464-8af1-d8c7206e6d6f")]
            public virtual RepoItemInfo keypad4Info
            {
                get
                {
                    return _keypad4Info;
                }
            }

            /// <summary>
            /// The keypad5 item.
            /// </summary>
            [RepositoryItem("1ec46429-65e9-46a3-91f4-96b58db4a37d")]
            public virtual Ranorex.Button keypad5
            {
                get
                {
                    return _keypad5Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad5 item info.
            /// </summary>
            [RepositoryItemInfo("1ec46429-65e9-46a3-91f4-96b58db4a37d")]
            public virtual RepoItemInfo keypad5Info
            {
                get
                {
                    return _keypad5Info;
                }
            }

            /// <summary>
            /// The keypad6 item.
            /// </summary>
            [RepositoryItem("f654682e-3c9c-4a5b-b6fa-7a2ccbb6f2e1")]
            public virtual Ranorex.Button keypad6
            {
                get
                {
                    return _keypad6Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad6 item info.
            /// </summary>
            [RepositoryItemInfo("f654682e-3c9c-4a5b-b6fa-7a2ccbb6f2e1")]
            public virtual RepoItemInfo keypad6Info
            {
                get
                {
                    return _keypad6Info;
                }
            }

            /// <summary>
            /// The keypad7 item.
            /// </summary>
            [RepositoryItem("1bac706b-38f2-418e-bbcb-5647fb7941d2")]
            public virtual Ranorex.Button keypad7
            {
                get
                {
                    return _keypad7Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad7 item info.
            /// </summary>
            [RepositoryItemInfo("1bac706b-38f2-418e-bbcb-5647fb7941d2")]
            public virtual RepoItemInfo keypad7Info
            {
                get
                {
                    return _keypad7Info;
                }
            }

            /// <summary>
            /// The keypad8 item.
            /// </summary>
            [RepositoryItem("4a1c3710-9089-4b9d-bf88-65aae847d1bb")]
            public virtual Ranorex.Button keypad8
            {
                get
                {
                    return _keypad8Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad8 item info.
            /// </summary>
            [RepositoryItemInfo("4a1c3710-9089-4b9d-bf88-65aae847d1bb")]
            public virtual RepoItemInfo keypad8Info
            {
                get
                {
                    return _keypad8Info;
                }
            }

            /// <summary>
            /// The keypad9 item.
            /// </summary>
            [RepositoryItem("43db0f4b-1895-47c1-98ef-14a9fda4a0f1")]
            public virtual Ranorex.Button keypad9
            {
                get
                {
                    return _keypad9Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad9 item info.
            /// </summary>
            [RepositoryItemInfo("43db0f4b-1895-47c1-98ef-14a9fda4a0f1")]
            public virtual RepoItemInfo keypad9Info
            {
                get
                {
                    return _keypad9Info;
                }
            }

            /// <summary>
            /// The keypad0 item.
            /// </summary>
            [RepositoryItem("a5d7d031-563e-46b9-8b9a-7f3754be86d4")]
            public virtual Ranorex.Button keypad0
            {
                get
                {
                    return _keypad0Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The keypad0 item info.
            /// </summary>
            [RepositoryItemInfo("a5d7d031-563e-46b9-8b9a-7f3754be86d4")]
            public virtual RepoItemInfo keypad0Info
            {
                get
                {
                    return _keypad0Info;
                }
            }

            /// <summary>
            /// The EnterButton item.
            /// </summary>
            [RepositoryItem("2ce707c9-ad62-45f6-bc94-ebad5981a8b2")]
            public virtual Ranorex.Button EnterButton
            {
                get
                {
                    return _enterbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EnterButton item info.
            /// </summary>
            [RepositoryItemInfo("2ce707c9-ad62-45f6-bc94-ebad5981a8b2")]
            public virtual RepoItemInfo EnterButtonInfo
            {
                get
                {
                    return _enterbuttonInfo;
                }
            }

            /// <summary>
            /// The StoreLogIn item.
            /// </summary>
            [RepositoryItem("8ff6dc1d-3ab5-4b26-9826-dc47dd9facab")]
            public virtual Ranorex.Text StoreLogIn
            {
                get
                {
                    return _storeloginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StoreLogIn item info.
            /// </summary>
            [RepositoryItemInfo("8ff6dc1d-3ab5-4b26-9826-dc47dd9facab")]
            public virtual RepoItemInfo StoreLogInInfo
            {
                get
                {
                    return _storeloginInfo;
                }
            }

            /// <summary>
            /// The storeLoginKeypad9 item.
            /// </summary>
            [RepositoryItem("c10db81a-bf65-47d5-8dd0-c745900ef3d1")]
            public virtual Ranorex.Button storeLoginKeypad9
            {
                get
                {
                    return _storeloginkeypad9Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The storeLoginKeypad9 item info.
            /// </summary>
            [RepositoryItemInfo("c10db81a-bf65-47d5-8dd0-c745900ef3d1")]
            public virtual RepoItemInfo storeLoginKeypad9Info
            {
                get
                {
                    return _storeloginkeypad9Info;
                }
            }

            /// <summary>
            /// The storeLoginOkBtn item.
            /// </summary>
            [RepositoryItem("e3335353-da32-4362-b552-d4f1c61ebcb1")]
            public virtual Ranorex.Button storeLoginOkBtn
            {
                get
                {
                    return _storeloginokbtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The storeLoginOkBtn item info.
            /// </summary>
            [RepositoryItemInfo("e3335353-da32-4362-b552-d4f1c61ebcb1")]
            public virtual RepoItemInfo storeLoginOkBtnInfo
            {
                get
                {
                    return _storeloginokbtnInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
