///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SCO_Test.Recording_Modules.ReportRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The test_runTodaySummaryReportByCashier recording.
    /// </summary>
    [TestModule("d4c2059e-457d-4091-8e49-39ceee360888", ModuleType.Recording, 1)]
    public partial class Test_runTodaySummaryReportByCashier : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SCO_Test.SCO_TestRepository repository.
        /// </summary>
        public static global::SCO_Test.SCO_TestRepository repo = global::SCO_Test.SCO_TestRepository.Instance;

        static Test_runTodaySummaryReportByCashier instance = new Test_runTodaySummaryReportByCashier();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Test_runTodaySummaryReportByCashier()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Test_runTodaySummaryReportByCashier Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.AssistanceButton' at 63;23.", repo.NCRNEXTGENUI2.AssistanceButtonInfo, new RecordItemIndex(0));
            repo.NCRNEXTGENUI2.AssistanceButton.Click("63;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.StoreLogIn1' at Center.", repo.NCRNEXTGENUI2.SomeContainer.StoreLogIn1Info, new RecordItemIndex(2));
            repo.NCRNEXTGENUI2.SomeContainer.StoreLogIn1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.Text9' at 9;15.", repo.NCRNEXTGENUI2.SomeContainer.Text9Info, new RecordItemIndex(4));
            repo.NCRNEXTGENUI2.SomeContainer.Text9.Click("9;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(5));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.TextOK' at 24;0.", repo.NCRNEXTGENUI2.SomeContainer.TextOKInfo, new RecordItemIndex(6));
            repo.NCRNEXTGENUI2.SomeContainer.TextOK.Click("24;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(7));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.Text9' at 9;22.", repo.NCRNEXTGENUI2.SomeContainer.Text9Info, new RecordItemIndex(8));
            repo.NCRNEXTGENUI2.SomeContainer.Text9.Click("9;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(9));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.TextOK' at Center.", repo.NCRNEXTGENUI2.SomeContainer.TextOKInfo, new RecordItemIndex(10));
            repo.NCRNEXTGENUI2.SomeContainer.TextOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.Reporting' at Center.", repo.NCRNEXTGENUI2.ReportingInfo, new RecordItemIndex(11));
            repo.NCRNEXTGENUI2.Reporting.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.ItemDescription1' at Center.", repo.NCRNEXTGENUI2.ItemDescription1Info, new RecordItemIndex(12));
            repo.NCRNEXTGENUI2.ItemDescription1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.RunReport' at Center.", repo.NCRNEXTGENUI2.RunReportInfo, new RecordItemIndex(13));
            repo.NCRNEXTGENUI2.RunReport.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='  Assistance - Today Summary by Cashier') on item 'NCRNEXTGENUI2.TextAssistanceTodaySummaryByCash'.", repo.NCRNEXTGENUI2.TextAssistanceTodaySummaryByCashInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.TextAssistanceTodaySummaryByCashInfo, "Text", "  Assistance - Today Summary by Cashier");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.StoreButton8' at Center.", repo.NCRNEXTGENUI2.StoreButton8Info, new RecordItemIndex(15));
            repo.NCRNEXTGENUI2.StoreButton8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.StoreButton8' at Center.", repo.NCRNEXTGENUI2.StoreButton8Info, new RecordItemIndex(16));
            repo.NCRNEXTGENUI2.StoreButton8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.StoreButton8' at Center.", repo.NCRNEXTGENUI2.StoreButton8Info, new RecordItemIndex(17));
            repo.NCRNEXTGENUI2.StoreButton8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Press Here or           Scan Item') on item 'NCRNEXTGENUI2.PressHereOrScanItem'.", repo.NCRNEXTGENUI2.PressHereOrScanItemInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.PressHereOrScanItemInfo, "Text", "Press Here or           Scan Item");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
