///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SCO_Test.Recording_Modules.ReportRecordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The test_runTodaySalesReport recording.
    /// </summary>
    [TestModule("9e40a2e3-0a4d-4fc3-b1ed-8c3d6bbfe979", ModuleType.Recording, 1)]
    public partial class test_runTodaySalesReport : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SCO_Test.SCO_TestRepository repository.
        /// </summary>
        public static global::SCO_Test.SCO_TestRepository repo = global::SCO_Test.SCO_TestRepository.Instance;

        static test_runTodaySalesReport instance = new test_runTodaySalesReport();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public test_runTodaySalesReport()
        {
            N3_0 = "3.0";
            N6_0 = "6.0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static test_runTodaySalesReport Instance
        {
            get { return instance; }
        }

#region Variables

        string _N3_0;

        /// <summary>
        /// Gets or sets the value of variable N3_0.
        /// </summary>
        [TestVariable("cae95283-259f-4534-9001-0eb0fec58e0f")]
        public string N3_0
        {
            get { return _N3_0; }
            set { _N3_0 = value; }
        }

        string _N6_0;

        /// <summary>
        /// Gets or sets the value of variable N6_0.
        /// </summary>
        [TestVariable("0b520a2a-2583-47bb-9ed0-98a5e2bed7dc")]
        public string N6_0
        {
            get { return _N6_0; }
            set { _N6_0 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.AssistanceButton' at 63;23.", repo.NCRNEXTGENUI2.AssistanceButtonInfo, new RecordItemIndex(0));
            repo.NCRNEXTGENUI2.AssistanceButton.Click("63;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.StoreLogIn1' at Center.", repo.NCRNEXTGENUI2.SomeContainer.StoreLogIn1Info, new RecordItemIndex(2));
            repo.NCRNEXTGENUI2.SomeContainer.StoreLogIn1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.Text9' at 9;15.", repo.NCRNEXTGENUI2.SomeContainer.Text9Info, new RecordItemIndex(4));
            repo.NCRNEXTGENUI2.SomeContainer.Text9.Click("9;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(5));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.TextOK' at 24;0.", repo.NCRNEXTGENUI2.SomeContainer.TextOKInfo, new RecordItemIndex(6));
            repo.NCRNEXTGENUI2.SomeContainer.TextOK.Click("24;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(7));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.Text9' at 9;22.", repo.NCRNEXTGENUI2.SomeContainer.Text9Info, new RecordItemIndex(8));
            repo.NCRNEXTGENUI2.SomeContainer.Text9.Click("9;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(9));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.SomeContainer.TextOK' at Center.", repo.NCRNEXTGENUI2.SomeContainer.TextOKInfo, new RecordItemIndex(10));
            repo.NCRNEXTGENUI2.SomeContainer.TextOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.Reporting' at Center.", repo.NCRNEXTGENUI2.ReportingInfo, new RecordItemIndex(11));
            repo.NCRNEXTGENUI2.Reporting.Click();
            Delay.Milliseconds(1600);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'NCRNEXTGENUI2.ItemDescription1' at Center.", repo.NCRNEXTGENUI2.ItemDescription1Info, new RecordItemIndex(12));
            repo.NCRNEXTGENUI2.ItemDescription1.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(13));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(16));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(17));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(18));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(20));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(21));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -100000 units.", new RecordItemIndex(22));
            Mouse.ScrollWheel(-100000);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(23));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=550,Y=522}.", new RecordItemIndex(24));
            Mouse.MoveTo(550, 522);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.RunReport' at Center.", repo.NCRNEXTGENUI2.RunReportInfo, new RecordItemIndex(25));
            repo.NCRNEXTGENUI2.RunReport.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='           Sales - Today Summary') on item 'NCRNEXTGENUI2.TextSalesTodaySummary'.", repo.NCRNEXTGENUI2.TextSalesTodaySummaryInfo, new RecordItemIndex(26));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.TextSalesTodaySummaryInfo, "Text", "           Sales - Today Summary");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.StoreButton8' at Center.", repo.NCRNEXTGENUI2.StoreButton8Info, new RecordItemIndex(27));
            repo.NCRNEXTGENUI2.StoreButton8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.StoreButton8' at Center.", repo.NCRNEXTGENUI2.StoreButton8Info, new RecordItemIndex(28));
            repo.NCRNEXTGENUI2.StoreButton8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NCRNEXTGENUI2.StoreButton8' at Center.", repo.NCRNEXTGENUI2.StoreButton8Info, new RecordItemIndex(29));
            repo.NCRNEXTGENUI2.StoreButton8.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Press Here or           Scan Item') on item 'NCRNEXTGENUI2.PressHereOrScanItem'.", repo.NCRNEXTGENUI2.PressHereOrScanItemInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.NCRNEXTGENUI2.PressHereOrScanItemInfo, "Text", "Press Here or           Scan Item");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
